### ISSUE TITLE
Entity Deprecation Tracker (epic)

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-registry#1155]
One place to find all the related pieces
## Briefs:
 
- [x] [FBC Graph Deprecation/Delegation Identification](https://docs.google.com/document/d/1boGzDVBJgLM5-t9WYrnQQMceLI3fryOcRkJMhqokU3w/edit)
- [x] [OLMv0 Graph Deprecation/Delegation](https://docs.google.com/document/d/1ipnf5uMiGZh5GXt2ey3oxziFx9lZv0qiFmB8g54EFwQ/edit)
- [x] [OLMv1 Graph Deprecation/Delegation](https://docs.google.com/document/d/17SaY8i8oaNlqx-akyj0CZQllnEUrqoXGIPIFk_rDcsY/edit)

## RFCs:

- #1146 [FBC Graph Deprecation/Delegation Identification](https://docs.google.com/document/d/1EzefSzoGZL2ipBt-eCQwqqNwlpOIt7wuwjG6_8ZCi5s/)
- https://github.com/operator-framework/operator-controller/issues/452 [OLMv1 Graph Deprecation/Delegation](https://docs.google.com/document/d/1CYGANKILfzfOoWtHvyg4luF7i-cC1NRa7_1N9xTLatw/)
- https://github.com/operator-framework/operator-lifecycle-manager/issues/3060 [OLMv0 Graph Deprecation/Delegation](https://docs.google.com/document/d/1SLgERsnNwNN7PuABdzysmxYxzD-hiyh7yuJc1m2Hy98/)

### Need:

- #1150
   - https://github.com/operator-framework/operator-registry/pull/1151 (*)
- #1154 (*)
   - https://github.com/operator-framework/operator-registry/pull/1161
- https://github.com/operator-framework/operator-lifecycle-manager/issues/3098
- #1163 (*)
   - #1164
- https://github.com/operator-framework/operator-lifecycle-manager/issues/3099 (*)
   - https://github.com/operator-framework/operator-lifecycle-manager/pull/3106 
- https://github.com/operator-framework/operator-lifecycle-manager/issues/3103 (*)

### Nice to have:

- #1160 (*)
- #1162 (*)
- https://github.com/operator-framework/operator-lifecycle-manager/issues/3100
   - https://github.com/operator-framework/operator-lifecycle-manager/pull/3110
- https://github.com/operator-framework/operator-lifecycle-manager/issues/3104
- https://github.com/operator-framework/olm-docs/issues/318 (*)

### Not now:

- https://github.com/operator-framework/operator-controller/issues/525 (*)
- https://github.com/operator-framework/operator-controller/issues/526 (*)
- https://github.com/operator-framework/operator-controller/issues/527 (*)
